import { generate } from '../generate'
import { describe, it, expect } from 'vitest'

describe('generate 函数', () => {
  it('should convert simple interface to zod schema', async () => {
    const tsCode = `
      export interface User {
        name: string;
        age: number;
        isActive: boolean;
      }
    `

    const result = await generate(tsCode)
    expect(result).toMatchInlineSnapshot(`
      {
        "code": "// generated by valype
      import { z } from "zod/v4";

      export const UserSchema = z.object({
        name: z.string(),
        age: z.number(),
        isActive: z.boolean(),
      });

      ",
        "exports": [
          {
            "interface": "User",
            "schema": "UserSchema",
          },
        ],
      }
    `)
  })

  it('should handle optional properties', async () => {
    const tsCode = `
      export interface Product {
        id: string;
        name?: string;
        price: number;
      }
    `

    const { code: result } = await generate(tsCode)
    expect(result).toContain('name: z.string().optional()')
  })

  it('should handle array types', async () => {
    const tsCode = `
      export interface Order {
        items: string[];
        quantities: number[];
      }
    `

    const { code: result } = await generate(tsCode)
    expect(result).toContain('items: z.array(z.string())')
    expect(result).toContain('quantities: z.array(z.number())')
  })

  it('should handle nested interfaces', async () => {
    const tsCode = `
      export interface Address {
        street: string;
        city: string;
      }

      export interface Person {
        name: string;
        address: Address;
      }
    `

    const { code: result } = await generate(tsCode)
    expect(result).toContain('export const AddressSchema = z.object({')
    expect(result).toContain('address: AddressSchema')
  })
})
