import { createApp } from 'vue'
import './style.css'
import App from './App.vue'
// @ts-expect-error - this is a virtual module generated by valype
import { validateUser } from './user.valype'

console.log(`validateUser ==>`, validateUser)

createApp(App).mount('#app')
