import { createApp } from 'vue'
import './style.css'
import App from './App.vue'
// @ts-expect-error - this is a virtual module generated by valype
import { UserSchema } from './user.valype'

console.log(`UserSchema ==>`, UserSchema)

createApp(App).mount('#app')
