name: Publish to NPM

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build packages
        run: bun run -b build

      - name: Publish to NPM
        run: |
          cd packages/valype && bun publish
          cd ../plugin && bun publish
          cd ../typescript-plugin && bun publish
        env:
          # it seemed like bun uses NPM_CONFIG_TOKEN to auth
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
